notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
    - KitaitiMakoto@gmail.com
rvm:
  - 2.1
  - 2.2
  - 2.3.0
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
env: TEST_UNIT_MAX_DIFF_TARGET_STRING_SIZE=9999999999
